return {
  mocha = {
    rosewater = "#e7b2b6", -- Adapted based on the softer, lighter red tones in Maia
    flamingo = "#e39898", -- Derived from the slightly muted red tones
    pink = "#eaa4b8", -- Inspired by the warmer pink tones in Maia
    mauve = "#ae88f5", -- A cooler purple tone based on Maia's style
    red = "#f76c7c", -- From Sonokai Maia red
    maroon = "#db7f88", -- Adapted to fit the darker reddish tones in Maia
    peach = "#f3a96a", -- From Sonokai Maia orange
    yellow = "#e3d367", -- From Sonokai Maia yellow
    green = "#9cd57b", -- From Sonokai Maia green
    teal = "#88c1b4", -- Adapted to fit the teal family in Maia
    sky = "#7fc9e6", -- Adapted based on Maia's blue
    sapphire = "#68b6d8", -- Slightly darker blue for sapphire
    blue = "#78cee9", -- From Sonokai Maia blue
    lavender = "#a492f5", -- A lighter purple to fit Maia's tones
    text = "#e1e2e3", -- From Sonokai Maia fg
    subtext1 = "#cbd9d8", -- From Sonokai Maia fg2
    subtext0 = "#aebbbc", -- Derived from Sonokai Maia style
    overlay2 = "#899a9b", -- Adapted from the Sonokai grey shades
    overlay1 = "#7f8c8e", -- Slightly darker grey
    overlay0 = "#6a787a", -- A deeper grey tone
    surface2 = "#353f46", -- From Sonokai Maia bg2
    surface1 = "#3a444b", -- From Sonokai Maia bg3
    surface0 = "#313b42", -- From Sonokai Maia bg1
    base = "#273136", -- From Sonokai Maia bg0
    mantle = "#21282c", -- From Sonokai Maia bg_dim
    crust = "#1c1e1f", -- From Sonokai Maia black
  },
  macchiato = {
    rosewater = "#e8cdc9", -- New color inspired by "rosewater", softer pinkish hue
    flamingo = "#e4b3b3", -- New color for "flamingo", a muted reddish-pink
    pink = "#f5c2e7", -- Direct from Sonokai (default)
    mauve = "#bda4d8", -- New color for "mauve", a blend of purple and pink
    red = "#fc5d7c", -- Direct from Sonokai (default)
    maroon = "#d88a8a", -- New color for "maroon", deeper and darker than flamingo
    peach = "#f39660", -- Direct from Sonokai (default)
    yellow = "#e7c664", -- Direct from Sonokai (default)
    green = "#9ed072", -- Direct from Sonokai (default)
    teal = "#7ac7c7", -- New color for "teal", a cool cyan-green
    sky = "#76b6ce", -- New color for "sky", inspired by a light blue-cyan mix
    sapphire = "#5e9bb0", -- New color for "sapphire", darker blue-cyan shade
    blue = "#76cce0", -- Direct from Sonokai (default)
    lavender = "#b39df3", -- Direct from Sonokai (default)
    text = "#e2e2e3", -- Direct from Sonokai (default)
    subtext1 = "#c2c4cc", -- New color for "subtext1", a lighter gray
    subtext0 = "#a8abb6", -- New color for "subtext0", a medium gray
    overlay2 = "#8b919f", -- New color for "overlay2", darker than subtext0
    overlay1 = "#7f849c", -- Direct from Sonokai (default)
    overlay0 = "#6c7086", -- Direct from Sonokai (default)
    surface2 = "#4b4f61", -- New color for "surface2", inspired by darker grays
    surface1 = "#414550", -- Direct from Sonokai (default)
    surface0 = "#313244", -- Direct from Sonokai (default)
    base = "#1e1e2e", -- Direct from Sonokai (default)
    mantle = "#181825", -- Direct from Sonokai (default)
    crust = "#11111b", -- Direct from Sonokai (default)
  },
}
